### ISSUE TITLE
Add Multimedia to a Question

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#303]
URL: http://testing-engine.camelcasetech.com/admin/tests/1/questions/1/edit
Path: Admin> Tests> Tests> Show> Test Questions> Edit
Description: Cannot add video file to a question.
![image](https://user-images.githubusercontent.com/11155105/38023968-50dda376-328c-11e8-866a-7b2b3e4546ed.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
I think this issue already fixed somewhere else, but please check

**Comment by HeshamHassan** [comment]
I tested this issue today and it still presents

**Comment by ahmedelbougha** [comment]
Thanks @HeshamHassan, we will confirm the issue En Shaa Allah. 
@mahmoud-hussien1, please check

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
20/09/2018

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, please check and confirm.

**Comment by HeshamHassan** [comment]
Not solved yet. check the screenshot below:
![image](https://user-images.githubusercontent.com/11155105/45996742-f0fc3f00-c0a5-11e8-8036-c2a0d1ddb739.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
What is the size/format of the video?

**Comment by HeshamHassan** [comment]
It was .AVI & .MP4.
Kindly provide me with the supported format and the supported maximum size.

**Comment by ahmedelbougha** [comment]
Yes, it supports MP4 and the maximum size is about 5MB

**Comment by HeshamHassan** [comment]
Done
