### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/testing-engine#326]
@ahmedelbougha as per Lamia Email today to Ahmed Elbougha

**Comment by ahmedelbougha** [comment]
@Ali-Galal @LamiaSalah 
Tuesday: 22/05/2018

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise the delivery date

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Home page and logo uploaded
Note the home page is experimental and not final yet, we need you final comments urgently to finish this as soon as possible

**Comment by LamiaSalah** [comment]
@ahmedelbougha please find my comments:

- [x] Logo is very big and not fitting with the template.
- [ ] Section 2 missing the 4 icons in the template with the text in the attachment I sent
- [x] Titles in the Certification Products not matching with what I sent
- [x] Size fo the 1st photo on the left not matching with other 2, please advise the size you need.
- [x] Section 4, need to be with less hight and the text need to match the size of the photo
- [ ] Section 5 (Join now) need to add the photo sent in my mail. 
- [x] SEction 6: The way the text added is not like the original layout of the template. Please make text below image and not over it. 
- [x] Delete arrows at the bottom

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and let's know the estimated date.

**Comment by mahmoud-hussien1** [comment]
31/05/2018

**Comment by LamiaSalah** [comment]
@ahmedelbougha please make the top header white, the logo couldn't be displayed on a colored background like it is now

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah can you inform me with the information blow?

- size of the logo.

- send the 4 icons for section 2 (images in mail are not include those icons).

- those are titles for Certification Products that i saw in the word file and they are matching production. please confirm that or explain what you want.

     1. State of the art authoring engine and SaaS hosting platform.
     2. Validate soft skills, business skills, technical skills, or vocational skills all in one place
     3. Host your own testing center
![screenshot from 2018-05-31 12 12 10](https://user-images.githubusercontent.com/35919348/40776953-98bca01c-64cc-11e8-854e-47b698d37c1b.png)

- in section 5 i added photo 5 like described in word file but, the image is very big so, what i have to do now. resize the section to be bigger or make the whole image appear in the section but it will be stretched.

- are you want something like that(for you last comment).
![screenshot from 2018-05-31 12 41 34](https://user-images.githubusercontent.com/35919348/40778073-31e1a5fa-64d0-11e8-9da1-33f8dc72a431.png)

- for section 6 is that you want?
![screenshot from 2018-05-31 12 48 32](https://user-images.githubusercontent.com/35919348/40778289-fcfc6d88-64d0-11e8-9430-fb7f4dbd4f47.png)

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 

- You need to advise the logo size based on the template.
- the 4 icons are originally in the template as attached, but you removed it 
![capture](https://user-images.githubusercontent.com/37042927/40778677-55216b02-64d2-11e8-891d-1390f749edc9.PNG)
- I mean the tabs here 
![capture](https://user-images.githubusercontent.com/37042927/40778752-a0f283e0-64d2-11e8-86ce-57dfe05fcd68.PNG)
- We can resize the photo to fit the specified place in the template, no need toa dd it very big
- Yes
- Yes, this could work

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
in Certification Products section, i think photo should be with width 350px and height 235px

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
The 4 icons are not included in the version of the template we have, the template only provides place holders like:
![home3-ft-04](https://user-images.githubusercontent.com/8982139/40886720-963e4d86-673d-11e8-850f-9c8718157ecd.png)
![home4-logo](https://user-images.githubusercontent.com/8982139/40886721-9a6e9406-673d-11e8-9c1d-04bc49693c24.png)

So, please send us another icons set to use them.

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah we need the image in "join now" section to be in width 1308px and height 371px.

**Comment by LamiaSalah** [comment]
![1308x371](https://user-images.githubusercontent.com/37042927/40904313-a2a19036-67da-11e8-9b34-7f60a7347418.jpg)

**Comment by LamiaSalah** [comment]
![3](https://user-images.githubusercontent.com/37042927/40905163-6fa49432-67dd-11e8-8928-fac88ca5cbd4.jpg)
![4](https://user-images.githubusercontent.com/37042927/40905165-6fcadd0e-67dd-11e8-8056-d78b30ff8f0b.jpg)
![1](https://user-images.githubusercontent.com/37042927/40905166-6ff2d1ba-67dd-11e8-97d5-94b984b56f12.jpg)
![2](https://user-images.githubusercontent.com/37042927/40905167-70198dd2-67dd-11e8-8bb9-c816c31c048e.jpg)

**Comment by LamiaSalah** [comment]
1st one for reports
2nd for test authoring
3 rd for system requirements
4th for features and benefits

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise status

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah it's in review and will be merged to production today.

**Comment by ahmedelbougha** [comment]
merged
@LamiaSalah 
Issues fixed, please confirm

**Comment by LamiaSalah** [comment]
@ahmedelbougha there are still issues with:

- The logo, it's distorted.
- The spaces between each section is very big
- the font used is not the one included in the template, this one does not look good.
- in 'Why choose Us' section, the photo size got very small compared to the text, you need to keep the proportion between both

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
is that good with you?
![screenshot from 2018-06-13 15 37 50](https://user-images.githubusercontent.com/35919348/41354692-e7bab458-6f1f-11e8-9951-18f405d273f1.png)

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 please make the photo fit with the text size, increase the text size if needed

**Comment by LamiaSalah** [comment]
@ahmedelbougha pleases advise of the status of the rest of the points raised in this issue

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please confirm the status of the following points by end of middle of today:

- The logo, it's distorted.
- The spaces between each section is very big
- the font used is not the one included in the template, this one does not look good.
- in 'Why choose Us' section, the photo size got very small compared to the text, you need to keep the proportion between both

**Comment by ahmedelbougha** [comment]
@LamiaSalah in regard to "Why Choose Us" section, we added that image on our own from the group of images you sent for SkillsBuilder not SkilledMatrix, so please provide us with another image  with the following size 
width: 1308px
height: 371px

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please send us the logo size you wish, currently the distorted logo is width: 150px height: 30px.
While the original size of logo is width: 415px height: 164px, so please send us the new size (or at least width or height) we can make it in the appropriate way.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
We have compared the fonts in the template with the one used in the homepage, they are the same, please advise.

**Comment by LamiaSalah** [comment]
![sm logo color vector_001](https://user-images.githubusercontent.com/37042927/41584820-93c0e9ca-73a8-11e8-990c-8c6d2f678775.png)
Attached is the logo with the required dimensions

**Comment by LamiaSalah** [comment]
As for the font, could we use another good looking one please, not sure what the available fonts are

**Comment by LamiaSalah** [comment]
@ahmedelbougha please note the following:
- [x] Remove the red tab on the main banner
- [x] Remove the black search bar below and shift the section below upward
- [x] In the 4 icons section, please keep only the titles I sent you and remove the one included in the template
- [ ] Links of Certification products are not working properly
- [ ] The three photos below are not aligned and not the same size

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
- i commented this comment before and photo didn't updated.
"in Certification Products section, i think photo should be with width 350px and height 235px".

- for Links of Certification products, it redirects you to tests page if you logged in or fail. please give me the links you want us to update.

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 I'm not sure I understand what you mean. The three photos now are aligned, I guess they have been fixed.

For the links, I'm talking about the 4 links just under the title Certification Products. When you click 'Soft Skills' for example the photos change. As for the pages, I'm unable to give you their linkI'm waiting for your updates about to work on it

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
the links should be filters for photos. are you want this photos belong to all categories (when click on any filter link all photos appear). if not, please tell me each photo belong to each filter.

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1  there's an issue with the photos if you click 'soft skills' one of the 3 photos disappears.

Also the 4 icons above, they still have the old text in the template with the new one added, please update

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 Any updates? please note that the format of the home page is completely damaged.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
@mahmoud-hussien1 already worked/finished your comments, and updating his changes, I didn't merge them yet.
@LamiaSalah 
In regard to to your comment 

> there's an issue with the photos if you click 'soft skills' one of the 3 photos disappears.
> Also the 4 icons above, they still have the old text in the template with the new one added, please update
@mahmoud-hussien1 already replied
> the links should be filters for photos. are you want this photos belong to all categories (when click on any filter link all photos appear). if not, please tell me each photo belong to each filter.

Please advise.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Would you please reply my above comment so we can close this ticket

**Comment by LamiaSalah** [comment]
@ahmedelbougha attached is are some details about the home page. I'm still finalizing the rest of the links and will get back to you. You can start working on this until I update you with the rest.

**Comment by LamiaSalah** [comment]
@ahmedelbougha please use this doc for final Homepage content, links and layout
[Skilled Matrix Home page.docx](https://github.com/camelcasetechsd/testing-engine/files/2248694/Skilled.Matrix.Home.page.docx)
. Please let's talk regarding the menu bar tabs.
- Hide the word العربية for now and increase the logo size without showing the frame around it, it looks odd.

**Comment by ahmedelbougha** [comment]
Fixed, please check and confirm

**Comment by LamiaSalah** [comment]
Thanks, Changes are applied except for:

- the logo, it's still small and pixilated with a frame
- The lay out of the sub menues still in 2 lines

Two more things:

- As discussed earlier, can you change the font to the same as Skills Builder Pro?
- For Why Choose Us section? please allign the text in the space available
- in the last section, 2nd photo " Certifying Organizations' please change the text to:
Establish a private portal to deliver standard tests to your employees. 

I'll send you details for the footer shortly

**Comment by ahmedelbougha** [comment]
@LamiaSalah 

- I increase the size of logo, if does not fit with you, please send me the size you need
- The menu is not broken into two lines, but as you told me yesterday I'll take the logo a bit left 
- In regard to Font, as discussed please send me the font and size you want and I'll apply it  En Shaa Allah, but changing the font  of the whole site into Skillsbuilder Pro is not an easy change and it may require time/cost estimation as enhancement.
-  "Why Choose Us" section: please elaborate more what do you mean
- The image shall look like this, please confirm
![smtx](https://user-images.githubusercontent.com/8982139/43713913-8930047a-997b-11e8-8d3e-d52e3422f083.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha 

- You can just change the font of the home page and menu bar to the same as SBP, no need to change the full site.
- For 'Why choose us' section. The font is aligned top left and the rest of the space is empty. It needs to fit the full space in relation with the photo added.
- The title needs to be the same for Certifying Organizations, I mean the text that appears when the blue background appears.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
- Please decide the font style/type and size that you need to apply to home page and let me know.
- Choose us section has been fixed
- Title of Certifying Organizations and similar items has been fixed

**Comment by ahmedelbougha** [comment]
@LamiaSalah @HeshamHassan 
Please check the home page confirm it's fine and close the issue.

**Comment by LamiaSalah** [comment]
The font issue is still the same. Please don't make the menu bar icons in caps lock,only first letters.
Also the choose us section still not fixed

**Comment by ahmedelbougha** [comment]
@MoatazAbdAlmageed 
1- logo to right
2- upper case letters

**Comment by MoatazAbdAlmageed** [comment]
@ahmedelbougha Done, Please check

**Comment by LamiaSalah** [comment]
@ahmedelbougha please delete the section' Why choose us' from the page

**Comment by LamiaSalah** [comment]
@ahmedelbougha  
- [ ] Under the main picture in the homepage, there are 4 sections (Features & Benefits, - Reports Analytics etc) that have broken links
![image](https://user-images.githubusercontent.com/11155105/48052186-5882cf80-e1b8-11e8-8832-a2e9287322b8.png)

- [ ] Also Under Certification Products, the 3 pictures that show read more when you hover over, have broken links, they direct to a white page.
![image](https://user-images.githubusercontent.com/11155105/48052277-89630480-e1b8-11e8-8ed1-89ecd22a71aa.png)

- [ ] All links at the footer need to be fixed, they are not working.
![image](https://user-images.githubusercontent.com/11155105/48052300-9849b700-e1b8-11e8-9b19-f37fa07d6663.png)

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
for the tow sections(certification products section and the section under the main picture), tell me the links to put them in those sections.

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 for the 1st section under the header:

Features and Benefits: Skilled-Matrix-Solutions/Test-Authoring-and-Hosting/Features-and-Benefits 
Reports and Analytics:  Skilled-Matrix-Solutions/Test-Authoring-and-Hosting/Reports-and-Analytics 
Test Authoring: Skilled-Matrix-Solutions/Test-Authoring-and-Hosting
System Requirements: Skilled-Matrix-solutions/System-Requirements

for the certification products links:
1st photo:http://skilledmatrix.com/About-Us/The-Skilled-Matrix-Advantage
2nd photo:Partner-Programs/Corporate-Testing-Centres/Become-a-Corporate-TC
3rd photo:  http://skilledmatrix.com/Skilled-Matrix-Solutions

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah Thanks.
Tell me the links to replace with broken links in footer also.
send me and i will fix them today En Shaa Allah

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 This has been sent earlier to Ahmed. Please check Issue 347 for the footer

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah yes, links are sent but, they are broken for now.
we want new unbroken links (some one edit pages path).

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 please change the titles of the footer to be the same as the header menu with the same order and links

**Comment by LamiaSalah** [comment]
@ahmedelbougha this issue has been opened for so long and I'm not sure what the problem is. We need to discuss it through the phone to finalize it so please call me when you're available as you're out of reach.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
OK, let's have a meeting toady by 4:00 PM En Shaa Allah.

**Comment by LamiaSalah** [comment]
@ahmedelbougha   confirmed

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc
Please edit the contact bar with the follwoing details:
Washington, District of Columbia 20005, 1200 G Street, NW, Suite 800
T: 202-661-3533

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please edit phone number to be +1 (202)-661-3533  

also the issue couldn't be closed as there are some pending points at the page above.

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc please edit phone number to be +1 (202)-661-3533 - **working on this **
> 
> also the issue couldn't be closed as there are some pending points at the page above.

ok @LamiaSalah will check the remaining points next week

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @LamiaSalah 
we updated the contact bar with the new info and update our features links , please let me know if some thing remaining at home page

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @LamiaSalah 
please close this issue if done

**Comment by Ali-Galal** [comment]
@LamiaSalah please answer this ASAP

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc there's an issue with the site I can't access it.
![image](https://user-images.githubusercontent.com/37042927/50817310-139c2600-132c-11e9-8004-0a1fa84a4f7e.png)

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Home page is not working. Backend is working good.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc as discussed please change the font to that of SBP

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc as discussed please change the font to that of SBP

done, please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  can you please the titles and menu items bold as it was before? and also move the menu bar at the top to the right, it shouldn't be so close to the logo

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc update, please

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah
the titles and menu items bold done, please confirm and close.

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 Confirmed
