### ISSUE TITLE
Photos upload 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#327]
@ahmedelbougha uploading photos option is not available in all pages

**Comment by LamiaSalah** [comment]
@ahmedelbougha Any updates?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
We are investigating the issues, we will let you know the estimated date of finish.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
It was server permission issue, it's fixed now.

**Comment by LamiaSalah** [comment]
@ahmedelbougha the issue is still there and the browse tab is still not available to upload new photos.

**Comment by LamiaSalah** [comment]
@ahmedelbougha any updates??

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please write a complete scenario of how are you facing this, since I uploaded another photo today.

![testing engine admin](https://user-images.githubusercontent.com/8982139/40616202-72367bd2-628a-11e8-9795-f95e8f55d25e.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha After you click edit, there is no browse tab to upload a photo 
![capture](https://user-images.githubusercontent.com/37042927/40644902-02c60880-6325-11e8-978e-76142aa9f40d.PNG)

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Thursday 31/05/2018

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/29/issue-327-upload-pages-by-ckeditor/diff

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise, today is 7/6 and it was supposed to be delivered by 31/5

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah it's in review and will be merged to production today.

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Issue fixed please check and confirm

**Comment by LamiaSalah** [comment]
@ahmedelbougha  confirmed
