### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#333]
The content is currently added on two lines for the menu bar, could you please check this issue?

**Comment by HeshamHassan** [comment]
@LamiaSalah ... That's right:
![image](https://user-images.githubusercontent.com/11155105/41903820-8eeca8de-793f-11e8-9083-b4dc0e8ac4ad.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan @LamiaSalah 
We have limited space and size of menu bar that cannot afford what you put there in the time being, please compare this with what you did in http://skillsbuilderpro.com, of course we can work on something to make it better, but taking in mind the text you wrote in the menu links, I don't think that will make great improvement.

**Comment by LamiaSalah** [comment]
@ahmedelbougha the titles added has nothing to do with the main menu we added Ahmed in the home page content. There's a lot of duplication, for example, Certification is added 3 times, this is not something that was included in our requirements

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah @HeshamHassan 
This is a miss-use of CMS backend while creating menu items:
1- All the menu items appear in the menu bar are created by your team
2- The word `Certification` is not displayed 3 times, it's displayed 4 times as following:
  - Certification Testing Products
  - Certification Partner Programs
  - Certification Candidates
  - Certification Partner Programs
All of the above are first level menu items, so it's normal for them to appear in the main menu.
The problem Lamia as I told you before, the width of the menu cannot carry all of this text.

![te-menu](https://user-images.githubusercontent.com/8982139/42898460-8d198c94-8ac3-11e8-9e76-0986d6283dea.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha we need to delete Appointment and Test Preparation from the menu bar and edit Certificate to be Certifications. Underneath there will be 
Certification Testing Products
Certification Partner Programs
Certification Candidates
Certification Partner Programs

The menu should include the following only with the same order:

About                  Skilled Matrix        Certification                  Shopping Cart

**Comment by ahmedelbougha** [comment]
Fixed, check and confirm

**Comment by LamiaSalah** [comment]
Tabs are not fixed. Please check the info provided in the home page issue

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
I have read the document you put in #326 of Home Page.
This issue is different issue which is related to menu styling not to the content of the menu and not to content of home page, we have fixed the styling, moved the fixed menu items (Appointments, Admin, Profile, Certificates) to be all under one separate menu item at the right. Any menu items that needs to be created of structured you can do it yourself from `CMS > Menus`, please correct me if I missed something.

Any other issues related to the document attached to #326 should be there to avoid duplicating the effort of following up.

**Comment by LamiaSalah** [comment]
@ahmedelbougha Ok . But what is Appointments and certificates? I'm not sure I understand this

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
They are two system menu items (not created by CMS) related to Booking an Exam (Appointment) and List user certificates (Certificates)

**Comment by LamiaSalah** [comment]
@Ali-Galal do we need to have this in the drop down as it is? please advise

**Comment by ahmedelbougha** [comment]
@LamiaSalah , @Ali-Galal , @HeshamHassan 
Update issue please?

**Comment by LamiaSalah** [comment]
@ahmedelbougha the width of each tab need to be created as discussed

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
What is that? Please advise.

**Comment by LamiaSalah** [comment]
@ahmedelbougha the order of each tab from left to right as we discussed it earlier

**Comment by ahmedelbougha** [comment]
Thanks @LamiaSalah, but this is different issue, please open new issue and close this one and mark the new issue as feature.
