### ISSUE TITLE
Custom Reports

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#344]
The tables (Items) order in the instruction while modifying the created report; changes each time I change the joining factors. So, the results when running the report are not the same each time. and sometimes when running the report I get error.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please put complete scenario of failures

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
I will create a full scenario and attach it to you today.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly check the issue points below and watch the attached file beside each point:

- [ ] Edit previous report: Cannot add a new entity to a previous report. ( [Point 1 - Edit Report.zip](https://github.com/camelcasetechsd/testing-engine/files/2265746/Point.1.-.Edit.Report.zip) )
- [x] Creating a new report: report created as shown in the attachment cannot run. ( [Point 2 - Create Report.zip](https://github.com/camelcasetechsd/testing-engine/files/2265750/Point.2.-.Create.Report.zip) )
- [x] After creating a report, and when modifying it, the entities order has changed. It is not as the same as created form. ( [Point 3 - Report Entity Order.zip](https://github.com/camelcasetechsd/testing-engine/files/2265755/Point.3.-.Report.Entity.Order.zip) )

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I'm sorry, please send me a common format videos, as I cannot open **mht**

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Is word format applicable?
[Recorded Steps.docx](https://github.com/camelcasetechsd/testing-engine/files/2283249/Recorded.Steps.docx)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I'll call @Ali-Galal to make check with him.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
After our meeting...
Any update?

**Comment by mahmoud-hussien1** [comment]
fixed.

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
please, check.

**Comment by HeshamHassan** [comment]
**1st. point:** Still cannot add another entity to the report in the new report: After Meeting Report1
![image](https://user-images.githubusercontent.com/11155105/45286265-09892880-b4ee-11e8-85b5-e1bf4cddb0cb.png)
But with the second new report: After Meeting Report2, I can!!!!

**2nd. point: Done
3rd. point: Done**

**Comment by ahmedelbougha** [comment]
Fixed

**Comment by HeshamHassan** [comment]
Not yet!
Kindly check "After Meeting Report3"
I created it now.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Check again please.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close.

**Comment by HeshamHassan** [comment]
I check with an existing report "After Meeting Report3" and with a new report "After Meeting Report4"
it is the same result. 
Check the screenshot:
![image](https://user-images.githubusercontent.com/11155105/45813124-6baa1080-bcda-11e8-921d-ec198a0e85d9.png)
![image](https://user-images.githubusercontent.com/11155105/45813090-5634e680-bcda-11e8-96d0-541f6023ec0e.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I'm not sure what are you trying to show me, but I have some notes:
1- The screen shots you put don't reflect what I can see when editing those reports
2- Why are you linking the users table with itself?
3- If you are linking the users table with itself, why you are not using any columns in the join?

![3](https://user-images.githubusercontent.com/8982139/45828244-60fe7400-bcf8-11e8-94ec-03610d1c0d72.png)
![4](https://user-images.githubusercontent.com/8982139/45828245-61970a80-bcf8-11e8-9c96-e22061ca503d.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly check my comment and the report names: 
> I check with an existing report "After Meeting Report3" and with a new report "After Meeting Report4"
> it is the same result.

The first screenshot for the old report. The second screenshot for a new created report that made after your instructions to check for that error.
The 2 reports have the same issue, I created the report with "Users" table and saved it. I tried to modify the it then I got the same issue: 
![image](https://user-images.githubusercontent.com/11155105/45997169-63215380-c0a7-11e8-8b43-b2875b63b13b.png)
**_Note: I'm not trying to link a table with it self. It does make sense._**

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Let's setup a meeting today at 4:30 PM your time

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Kindly use this ID: 248-355-381
I'm waiting for you.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I'm there but it seems you are not.

**Comment by HeshamHassan** [comment]
https://global.gotomeeting.com/join/248355381

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
fixed

**Comment by HeshamHassan** [comment]
Done
